name: Angular Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        mkdir gh-pages
        cp -r dist/* gh-pages/
        cd gh-pages
        git init
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Deployed from GitHub Actions"
        git branch -M main  # Ensure we are on the main branch
        git remote add origin https://${{ github.token }}@github.com/${{ github.repository }}.git
        git push -u origin main:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove installed dependencies
      run: rm -rf node_modules

    - name: Cleanup
      run: |
        rm -rf gh-pages
      if: success()
